const QUIZ_DATA = {
    sig: {
    label: "Sisteme informatice",
    questions: [
      {q: "1. Se consideră tabelele: STUDENTI, PROFESORI. Care interogare returnează studenții și profesorii din provincie?", o: ["A. SELECT CodStud, NumeStud, LoculNasterii, Cod Prof, NumeProf, LoculNasterii FROM STUDENTI, PROFESORI WHERE LoculNasterii<>'Bucureşti';", "B. SELECT CodStud, NumeStud, LoculNasterii, Cod Prof, NumeProf, LoculNasterii FROM STUDENTI, PROFESORI WHERE LoculNasterii = 'Provincie';", "C. SELECT CodStud, NumeStud, LoculNasterii FROM STUDENTI WHERE LoculNasterii = 'Provincie' UNION SELECT CodProf, NumeStud, LoculNasterii FROM PROFESORI WHERE LoculNasterii = 'Provincie';", "D. SELECT CodStud, NumeStud, LoculNasterii FROM STUDENTI WHERE LoculNasterii <>'Bucureşti' UNION SELECT CodProf, NumeProf, LoculNasterii FROM PROFESORI WHERE LoculNasterii <>'Bucureşti';"], a: 3},
      {q: "2. Se consideră tabela: CHITANTE. Care interogare afișează zilele cu mai mult de 2 chitanțe?", o: ["A. SELECT NrChitanta, Suma, DataChitanta FROM CHITANTE WHERE COUNT(NrChitanta) > 2;", "B. SELECT NrChitanta, Suma, DataChitanta FROM CHITANTE HAVING COUNT(NrChitanta) > 2;", "C. SELECT DataChitanta FROM CHITANTE GROUP BY DataChitanta HAVING COUNT(NrChitanta) > 2;", "D. SELECT COUNT(DataChitanta) FROM CHITANTE WHERE DataChitanta IS Unique;"], a: 2},
      {q: "3. Tabela: ANGAJATI. Afișare nr. salariați per compartiment care începe cu 'A':", o: ["A. SELECT CodAngajat, Nume, Compartiment FROM ANGAJATI WHERE Nume like 'A%';", "B. SELECT COUNT(CodAngajat) AS Număr FROM ANGAJATI WHERE Nume like 'A%' GROUP BY Compartiment;", "C. SELECT CodAngajat FROM ANGAJATI WHERE Compartiment like 'A%';", "D. SELECT COUNT(CodAngajat) AS Număr, Compartiment FROM ANGAJATI WHERE Compartiment like 'A%' GROUP BY Compartiment;"], a: 3},
      {q: "4. Tabele: CLIENTI, FACTURI. Clienți fără facturi în 1 mai 2021:", o: ["A. SELECT * FROM Facturi LEFT JOIN Clienti ON CodCL = CodCL WHERE DataFact = '2021-05-01';", "B. SELECT Nume FROM Clienti INNER JOIN Facturi ON CodCL = CodCL WHERE DataFact = '2021-05-01';", "C. SELECT CodCL FROM Facturi WHERE DataFact NOT IN ('2021-05-01');", "D. SELECT Nume FROM Clienti WHERE CodCL NOT IN (SELECT CodCL FROM Facturi WHERE DataFact = '2021-05-01');"], a: 3},
      {q: "5. Tabela: ANGAJATI. Majorare salariu 1% pentru angajați în 2021:", o: ["A. UPDATE Angajati SET Salariu = Salariu + 1% WHERE DataAngajare = 2021;", "B. UPDATE Salariu FROM Angajati SET Salariu = Salariu * 1.01 WHERE DataAngajare BETWEEN '2021-01-01' AND '2021-12-31';", "C. UPDATE Angajati SET Salariu = Salariu + (Salariu * 0.01) WHERE YEAR(DataAngajare) = 2021;", "D. UPDATE Angajati SET Salariu = Salariu * 1.01 WHERE YEAR(DataAngajare) = 2021;"], a: 3},
      {q: "6. Tabela: ANGAJATI. Nr salariați per compartiment începând cu 'A':", o: ["A. SELECT COUNT(CodAngajat) FROM Angajati GROUP BY Compartiment;", "B. SELECT COUNT(CodAngajat) FROM Angajati WHERE Compartiment LIKE 'A%' GROUP BY Compartiment;", "C. SELECT Compartiment, COUNT(*) FROM Angajati GROUP BY Compartiment;", "D. SELECT Compartiment, COUNT(CodAngajat) FROM Angajati WHERE Compartiment LIKE 'A%' GROUP BY Compartiment;"], a: 3},
      {q: "7. Tabele: PROFESORI, FACULTATI. Afișare profesori și facultăți:", o: ["A. SELECT Nume, Facultate FROM Profesori, Facultati;", "B. SELECT P.Nume, F.Denumire FROM Profesori P JOIN Facultati F ON P.CodFac = F.CodFac;", "C. SELECT * FROM Profesori JOIN Facultati;", "D. SELECT P.Nume FROM Profesori P WHERE CodFac = CodFac;"], a: 1},
      {q: "8. Tabela: SALARIATI. Salariu > media companiei:", o: ["A. SELECT Nume FROM Salariati WHERE Salariu > AVG(Salariu);", "B. SELECT Nume FROM Salariati WHERE Salariu > (SELECT AVG(Salariu) FROM Salariati);", "C. SELECT Nume FROM Salariati WHERE Salariu > 0;", "D. SELECT AVG(Salariu) FROM Salariati;"], a: 1},
      {q: "9. Tabele: SALARIATI, FUNCTII. Funcții fără angajați:", o: ["A. SELECT * FROM Functii WHERE CodFunctie = NULL;", "B. SELECT * FROM Functii JOIN Salariati;", "C. SELECT * FROM Functii WHERE CodFunctie NOT IN (SELECT CodFunctie FROM Salariati);", "D. SELECT Cod_functie FROM Functii WHERE Cod_functie NOT IN (SELECT Cod_functie FROM Salariati WHERE Cod_functie IS NOT NULL);"], a: 3},
      {q: "10. Definiție sistem:", o: ["A. Un ansamblu de elemente interdependente care interacționează pentru a atinge un scop comun.", "B. Un set de date izolate.", "C. O listă de fișiere pe calculator.", "D. Un proces manual."], a: 0},
      {q: "11. Sistem informațional cuprinde:", o: ["A. Doar hardware și software.", "B. Doar datele introduse.", "C. Date, informații, fluxuri, proceduri, oameni, tehnologii.", "D. Doar baza de date."], a: 2},
      {q: "12. Componente sistem informatic:", o: ["A. Doar computerele.", "B. Hardware, software, date, proceduri, personal.", "C. Doar rețeaua.", "D. Doar aplicațiile."], a: 1},
      {q: "13. Structuri control programare:", o: ["A. Doar liniară.", "B. Doar ciclică.", "C. Doar decizională.", "D. Secvențială, alternativă (decizională), repetitivă (iterativă)."], a: 3},
      {q: "14. Ciclul prelucrare date:", o: ["A. Stocare, Afișare.", "B. Doar Introducere.", "C. Colectare, prelucrare, stocare, distribuție.", "D. Doar Prelucrare."], a: 2},
      {q: "15. Metodologii realizare sisteme:", o: ["A. Structurate (Waterfall), Agile, Prototipizare.", "B. Doar Waterfall.", "C. Doar Agile.", "D. Nu există metodologii."], a: 0},
      {q: "16. Afirmații corecte (Top-Down):", o: ["A. Metoda de la general la particular (descompunere succesivă).", "B. Metoda de la particular la general.", "C. Nu contează direcția.", "D. Este o metodă hardware."], a: 0},
      {q: "17. Nu este fază a ciclului de viață:", o: ["A. Analiză.", "B. Implementare.", "C. Depozitare fizică de hârtii.", "D. Mentenanță."], a: 2},
      {q: "18. SGBD (Sistem de Gestiune a Bazelor de Date):", o: ["A. Software pentru gestionarea bazelor de date (ex: SQL Server, Oracle).", "B. Un tip de hard disc.", "C. Un limbaj de programare.", "D. Un sistem de operare."], a: 0},
      {q: "19. Diagrame Gantt:", o: ["A. Instrument de planificare și monitorizare a proiectelor (timp).", "B. Diagramă de stocuri.", "C. O metodă de vânzare.", "D. O diagramă de rețea."], a: 0},
      {q: "20. Studiul sistemului existent:", o: ["A. Nu e necesar.", "B. Doar verificarea hardware-ului.", "C. Doar ștergerea datelor vechi.", "D. Identificarea punctelor tari/slabe și a fluxurilor informaționale."], a: 3},
      {q: "21. Metode tradiționale cerințe:", o: ["A. Interviuri, chestionare, observare, analiză documente.", "B. Doar interviuri.", "C. Doar chestionare.", "D. Nu există."], a: 0},
      {q: "22. Scop DFD (Data Flow Diagram):", o: ["A. Reprezentarea hardware.", "B. Reprezentarea financiară.", "C. Reprezentarea grafică a fluxului de date prin sistem.", "D. Doar pentru baze de date."], a: 3},
      {q: "23. Simbol DFD - Flux date:", o: ["A. Săgeată (vector) care indică direcția.", "B. Cerc.", "C. Dreptunghi.", "D. Pătrat."], a: 0},
      {q: "24. Raport cerințe conține:", o: ["A. Doar prețul.", "B. Obiective, constrângeri, funcționalități, date.", "C. Doar numele programatorilor.", "D. Doar tehnologia folosită."], a: 1},
      {q: "25. Documentație logică procese:", o: ["A. Facturi.", "B. Extrase cont.", "C. Specificații procedurale (pseudocod, tabele decizionale).", "D. Doar poze."], a: 3},
      {q: "26. Modelare conceptuală date:", o: ["A. Diagrama Entitate-Relație (DER).", "B. Diagrame de rețea.", "C. Diagrame de vânzări.", "D. Planuri de marketing."], a: 0},
      {q: "27. DER simbol entitate:", o: ["A. Cerc.", "B. Săgeată.", "C. Linie.", "D. Dreptunghi (nume entitate)."], a: 3},
      {q: "28. Afirmații incorecte DFD:", o: ["A. Fluxurile unesc procese.", "B. Procesele transformă datele.", "C. Entitățile externe sunt surse/destinații.", "D. Fluxurile pot exista fără procese."], a: 3},
      {q: "29. Prezentare informații rapoarte:", o: ["A. Tabelar, grafic, text (structurat).", "B. Doar tabelar.", "C. Doar grafic.", "D. Doar text."], a: 0},
      {q: "30. Alegere suport fizic ieșire:", o: ["A. Doar hârtie.", "B. Doar ecran.", "C. Ecran, imprimantă, fișier (PDF, Excel).", "D. Doar stocare pe bandă."], a: 2},
      {q: "31. Machetă document intrare:", o: ["A. Doar un cod.", "B. Doar o semnătură.", "C. Design formular/ecran pentru captură date.", "D. Nu există."], a: 2},
      {q: "32. Produse 50-100, sortare denumire:", o: ["A. SELECT * FROM Produse;", "B. SELECT * FROM Produse WHERE Pret > 50;", "C. SELECT * FROM Produse WHERE Pret BETWEEN 50 AND 100 ORDER BY Denumire;", "D. SELECT * FROM Produse ORDER BY Pret;"], a: 2},
      {q: "33. Produse 'papetarie' > 50:", o: ["A. SELECT * FROM Produse WHERE Categorie='papetarie';", "B. SELECT * FROM Produse WHERE Categorie='papetarie' AND Pret > 50;", "C. SELECT * FROM Produse WHERE Pret > 50;", "D. SELECT * FROM Produse;"], a: 1},
      {q: "34. Zile > 2 chitanțe:", o: ["A. SELECT * FROM Chitante;", "B. SELECT DataChitanta FROM Chitante;", "C. SELECT DataChitanta FROM Chitante GROUP BY DataChitanta HAVING COUNT(*) > 2;", "D. SELECT * FROM Chitante WHERE Suma > 2;"], a: 2},
      {q: "35. Nr salariați compartiment 'A':", o: ["A. SELECT * FROM Angajati;", "B. SELECT COUNT(*) FROM Angajati;", "C. SELECT COUNT(*) FROM Angajati WHERE Compartiment='A';", "D. SELECT COUNT(*) FROM Angajati WHERE Compartiment LIKE 'A%';"], a: 3},
      {q: "36. Nume/funcție vechime > 5 ani:", o: ["A. SELECT Nume, Functie FROM Angajati WHERE (YEAR(GETDATE())-YEAR(DataAngajare)) > 5;", "B. SELECT * FROM Angajati;", "C. SELECT Nume FROM Angajati;", "D. SELECT * FROM Angajati WHERE Vechime > 5;"], a: 0},
      {q: "37. Clienți fără facturi 10 ian 2021:", o: ["A. SELECT * FROM Clienti;", "B. SELECT Nume FROM Clienti WHERE CodCL NOT IN (SELECT CodCL FROM Facturi WHERE DataFact = '2021-01-10');", "C. SELECT * FROM Facturi;", "D. SELECT Nume FROM Clienti;"], a: 1},
      {q: "38. Furnizori TVA < 100 lei:", o: ["A. SELECT Nume FROM Furnizori WHERE TVA < 100;", "B. SELECT * FROM Furnizori;", "C. SELECT TVA FROM Furnizori;", "D. SELECT Nume FROM Furnizori WHERE TVA > 100;"], a: 0},
      {q: "39. Sumă totală pe oraș iulie 2021:", o: ["A. SELECT Suma FROM Facturi;", "B. SELECT Oras FROM Clienti;", "C. SELECT Oras, SUM(Suma) FROM Facturi JOIN Clienti ON Facturi.CodCL=Clienti.CodCL GROUP BY Oras;", "D. SELECT Oras, SUM(Suma) FROM Facturi JOIN Clienti ON Facturi.CodCL=Clienti.CodCL WHERE DataFact LIKE '2021-07%' GROUP BY Oras;"], a: 3},
      {q: "40. Ștergere clienți ultima săptămână:", o: ["A. DELETE FROM Clienti WHERE DataAdaugare > (CURRENT_DATE - 7);", "B. DELETE FROM Clienti;", "C. DELETE FROM Clienti WHERE Oras='Sibiu';", "D. DELETE FROM Clienti WHERE CodCL=1;"], a: 0},
      {q: "41. Micșorare 10% sume ghiseu 3, 2021:", o: ["A. UPDATE Chitante SET Suma = Suma + 0.1;", "B. UPDATE Chitante SET Suma = Suma - 0.1;", "C. UPDATE Chitante SET Suma = Suma * 0.9 WHERE NrGhiseu=3 AND YEAR(DataChitanta)=2021;", "D. UPDATE Chitante SET Suma = Suma * 1.1;"], a: 2},
      {q: "42. Listă client/produs vândut an curent:", o: ["A. SELECT * FROM Clienti;", "B. SELECT * FROM Facturi;", "C. SELECT C.Nume, P.Denumire FROM Clienti C JOIN Facturi F ON C.CodCL=F.CodCL JOIN Produse P ON F.CodProd=P.CodProd WHERE YEAR(DataFact)=YEAR(GETDATE());", "D. SELECT * FROM Produse;"], a: 2},
      {q: "43. Ștergere telefon clienți în afara Sibiului:", o: ["A. DELETE FROM Clienti;", "B. UPDATE Clienti SET Telefon=NULL WHERE Oras<>'Sibiu';", "C. UPDATE Clienti SET Telefon='000' WHERE Oras='Sibiu';", "D. DELETE FROM Clienti WHERE Oras<>'Sibiu';"], a: 1},
      {q: "44. Listă detaliată produs 'apa':", o: ["A. SELECT * FROM Produse;", "B. SELECT * FROM Produse WHERE Pret=10;", "C. SELECT * FROM Produse WHERE Denumire='suc';", "D. SELECT * FROM Produse WHERE Denumire='apa';"], a: 3},
      {q: "45. Ștergere economiști angajați înainte de 2020:", o: ["A. DELETE FROM Angajati;", "B. DELETE FROM Angajati WHERE Profesia='economist' AND YEAR(DataAngajare) < 2020;", "C. DELETE FROM Angajati WHERE Profesia='contabil';", "D. DELETE FROM Angajati WHERE DataAngajare > '2020-01-01';"], a: 1},
      {q: "46. Majorare salariu 1% angajați 2020:", o: ["A. UPDATE Angajati SET Salariu = Salariu + 0.01;", "B. UPDATE Angajati SET Salariu = Salariu * 1.01 WHERE YEAR(DataAngajare)=2020;", "C. UPDATE Angajati SET Salariu = Salariu * 1.1;", "D. UPDATE Angajati SET Salariu = Salariu * 1.05;"], a: 2},
      {q: "47. Valoare totală lună an curent:", o: ["A. SELECT Valoare FROM Facturi;", "B. SELECT SUM(Valoare) FROM Facturi WHERE MONTH(DataFact)=MONTH(GETDATE());", "C. SELECT SUM(Valoare) FROM Facturi;", "D. SELECT AVG(Valoare) FROM Facturi;"], a: 3},
      {q: "48. Calcul TVA anul curent:", o: ["A. SELECT SUM(Valoare * 0.19) FROM Facturi WHERE YEAR(DataFact)=YEAR(GETDATE());", "B. SELECT SUM(Valoare) FROM Facturi;", "C. SELECT AVG(Valoare) FROM Facturi;", "D. SELECT SUM(Valoare * 0.05) FROM Facturi;"], a: 0},
      {q: "49. Rezultat interogare PRODUSE:", o: ["A. Afișează tabelul cu produse filtrate/sortate conform cerinței.", "B. Nu afișează nimic.", "C. Șterge produsele.", "D. Adaugă produse."], a: 0},
      {q: "50. Rezultat interogare CLIENTI/FACTURI:", o: ["A. Șterge facturile.", "B. Adaugă clienți.", "C. Afișează lista clienților și a facturilor asociate.", "D. Nu returnează nimic."], a: 2}
    ]
  },
  micro: {
    label: "Microeconomie",
    questions: [
      {q: "51. Presupunem că prețul unui bun scade cu 10%, iar cantitatea cerută crește cu 15%. În aceste condiții:", o: ["A. veniturile încasate de producători scad", "B. veniturile încasate de producători cresc", "C. veniturile nu sunt influențate", "D. cheltuielile firmei cresc"], a: 1},
      {q: "52. Elasticitatea ofertei la preț este 1.5. Dacă prețul crește cu 10%, oferta va:", o: ["A. scădea cu 10%", "B. crește cu 10%", "C. crește cu 15%", "D. rămâne constantă"], a: 2},
      {q: "53. Afirmația falsă despre curba cererii:", o: ["A. panta este de obicei negativă", "B. arată relația directă preț-cantitate", "C. se deplasează la schimbarea veniturilor", "D. se deplasează la schimbarea preferințelor"], a: 1},
      {q: "54. Coeficientul elasticității cererii la venit:", o: ["A. pozitiv pentru bunuri inferioare", "B. negativ pentru bunuri normale", "C. pozitiv pentru bunuri normale", "D. zero pentru orice bun"], a: 2},
      {q: "55. Echilibrul consumatorului (utilitate marginală):", o: ["A. UMx/Px > UMy/Py", "B. UMx/Px = UMy/Py", "C. UMx/Px < UMy/Py", "D. UMx = UMy"], a: 1},
      {q: "56. Utilitatea marginală reprezintă:", o: ["A. satisfacția suplimentară obținută din consumul unei unități adiționale", "B. satisfacția totală", "C. media utilităților", "D. prețul bunului"], a: 0},
      {q: "57. Legea utilității marginale descrescânde:", o: ["A. utilitatea scade pe măsură ce consumul crește", "B. utilitatea crește continuu", "C. utilitatea este constantă", "D. nu există"], a: 0},
      {q: "58. Curba de indiferență arată:", o: ["A. combinații cu utilități diferite", "B. combinații de bunuri cu utilitate egală", "C. linia bugetului", "D. prețurile bunurilor"], a: 1},
      {q: "59. Combinație inaccesibilă bugetului:", o: ["A. se află pe linia bugetului", "B. se află deasupra liniei bugetului", "C. se află sub linia bugetului", "D. oricare"], a: 1},
      {q: "60. Panta liniei bugetului este determinată de:", o: ["A. venitul consumatorului", "B. preferințe", "C. raportul prețurilor bunurilor", "D. utilitatea marginală"], a: 2},
      {q: "61. În cazul ofertei perfect elastice:", o: ["A. prețul se schimbă, cantitatea nu", "B. cantitatea se schimbă la orice preț", "C. oferta este o dreaptă verticală", "D. prețul este zero"], a: 1},
      {q: "62. Capitalul circulant este cel care:", o: ["A. participă la un singur ciclu de producție", "B. este imobilizat pe termen lung", "C. nu se consumă", "D. se amortizează în 10 ani"], a: 0},
      {q: "63. Costul marginal reprezintă:", o: ["A. costul total împărțit la cantitate", "B. variația costului total pentru o unitate suplimentară", "C. costul fix", "D. profitul"], a: 1},
      {q: "64. Concurența perfectă presupune:", o: ["A. un singur producător", "B. bariere la intrare", "C. atomicitate, omogenitate, transparență", "D. diferențierea produselor"], a: 2},
      {q: "65. Monopolul se caracterizează prin:", o: ["A. un singur vânzător și mulți cumpărători", "B. produs omogen", "C. competiție liberă", "D. preț impus de piață"], a: 0},
      {q: "66. Legea randamentelor descrescânde se aplică:", o: ["A. pe termen lung", "B. când un factor de producție este fix", "C. când toți factorii sunt variabili", "D. în concurență perfectă"], a: 1},
      {q: "67. Costul fix:", o: ["A. variază cu producția", "B. este independent de volumul producției", "C. este egal cu costul marginal", "D. nu există"], a: 1},
      {q: "68. Venitul marginal în concurență perfectă:", o: ["A. este egal cu prețul", "B. este mai mare decât prețul", "C. este mai mic decât prețul", "D. zero"], a: 0},
      {q: "69. Profitul economic este:", o: ["A. venit total - cost contabil", "B. venit total - cost total (explicit + implicit)", "C. venit total - cost fix", "D. venit total - cost variabil"], a: 1},
      {q: "70. Elasticitatea cererii la preț este zero:", o: ["A. cerere perfect inelastică", "B. cerere perfect elastică", "C. cerere unitară", "D. nu există"], a: 0},
      {q: "71. Bunurile inferioare:", o: ["A. cererea crește când venitul crește", "B. cererea scade când venitul crește", "C. cererea este constantă", "D. nu au preț"], a: 1},
      {q: "72. Valoarea capitalului neamortizat:", o: ["A. cost istoric - amortizare acumulată", "B. cost istoric + amortizare", "C. zero", "D. prețul pieței"], a: 0},
      {q: "73. Costul total (CT):", o: ["A. CF + CV", "B. CF - CV", "C. CV / CF", "D. CFM + CM"], a: 0},
      {q: "74. Echilibrul pieței:", o: ["A. cererea > oferta", "B. oferta > cererea", "C. cererea = oferta", "D. prețul = 0"], a: 2},
      {q: "75. Ofertă perfect inelastică:", o: ["A. dreaptă orizontală", "B. dreaptă verticală", "C. curbă descrescătoare", "D. nu există"], a: 1},
      {q: "76. Efectul de substituție:", o: ["A. înlocuirea bunului mai scump cu unul mai ieftin", "B. creșterea venitului", "C. scăderea calității", "D. nu are loc"], a: 0},
      {q: "77. Externalitățile negative:", o: ["A. beneficii pentru terți", "B. costuri pentru terți", "C. nu afectează piața", "D. sunt subvenționate"], a: 1},
      {q: "78. Bunuri publice:", o: ["A. non-excludere și non-rivalitate", "B. excludere", "C. rivalitate", "D. privatizate"], a: 0},
      {q: "79. Costul de oportunitate:", o: ["A. valoarea celei mai bune alternative la care se renunță", "B. costul contabil", "C. profitul", "D. prețul"], a: 0},
      {q: "80. Factorii de producție clasici:", o: ["A. muncă, natură, capital", "B. informație, timp", "C. doar capital", "D. doar muncă"], a: 0},
      {q: "81. Productivitatea medie:", o: ["A. producție totală / cantitate factor", "B. producție totală * cantitate factor", "C. variație producție / variație factor", "D. zero"], a: 0},
      {q: "82. Productivitatea marginală:", o: ["A. variație producție / variație factor", "B. producție totală / factor", "C. producție totală", "D. preț"], a: 0},
      {q: "83. Concurența monopolistică:", o: ["A. produse diferențiate", "B. un singur vânzător", "C. produs omogen", "D. preț fix"], a: 0},
      {q: "84. Oligopolul:", o: ["A. câțiva vânzători mari", "B. mulți vânzători mici", "C. un singur vânzător", "D. nu există"], a: 0},
      {q: "85. Venitul total:", o: ["A. preț * cantitate", "B. preț + cantitate", "C. preț / cantitate", "D. profit"], a: 0},
      {q: "86. Cererea elastică:", o: ["A. $|E_p| > 1$", "B. $|E_p| < 1$", "C. $|E_p| = 1$", "D. $|E_p| = 0$"], a: 0},
      {q: "87. Cererea inelastică:", o: ["A. $|E_p| > 1$", "B. $|E_p| < 1$", "C. $|E_p| = 1$", "D. $|E_p| = 0$"], a: 1},
      {q: "88. Elasticitatea unitară:", o: ["A. $|E_p| > 1$", "B. $|E_p| < 1$", "C. $|E_p| = 1$", "D. $|E_p| = 0$"], a: 2},
      {q: "89. Înclinația marginală spre consum:", o: ["A. variație consum / variație venit", "B. consum total / venit", "C. venit / consum", "D. zero"], a: 0},
      {q: "90. PIB (Produs Intern Brut):", o: ["A. producția finală în interiorul țării", "B. producția naționalilor în străinătate", "C. consumul privat", "D. investițiile"], a: 0},
      {q: "91. Inflația:", o: ["A. creșterea generală a prețurilor", "B. scăderea prețurilor", "C. stagnare", "D. producție zero"], a: 0},
      {q: "92. Șomajul:", o: ["A. persoanele apte de muncă fără loc de muncă", "B. toți oamenii", "C. pensionarii", "D. copiii"], a: 0},
      {q: "93. Dobânda:", o: ["A. prețul capitalului împrumutat", "B. profitul", "C. salariul", "D. chiria"], a: 0},
      {q: "94. Renta funciară:", o: ["A. venit din pământ", "B. salariu", "C. profit", "D. dobândă"], a: 0},
      {q: "95. Cota de amortizare:", o: ["A. valoare amortizare / cost istoric", "B. cost istoric / valoare amortizare", "C. 0", "D. profit"], a: 0},
      {q: "96. Bugetul statului:", o: ["A. venituri - cheltuieli", "B. profit firmă", "C. salariu mediu", "D. investiții"], a: 0},
      {q: "97. Deficit bugetar:", o: ["A. cheltuieli > venituri", "B. venituri > cheltuieli", "C. venituri = cheltuieli", "D. zero"], a: 0},
      {q: "98. Excedent bugetar:", o: ["A. venituri > cheltuieli", "B. cheltuieli > venituri", "C. venituri = cheltuieli", "D. zero"], a: 0},
      {q: "99. Politica fiscală:", o: ["A. utilizarea impozitelor și cheltuielilor", "B. oferta de bani", "C. exporturi", "D. importuri"], a: 0},
      {q: "100. Politica monetară:", o: ["A. controlul masei monetare și ratelor dobânzii", "B. taxe", "C. cheltuieli stat", "D. salarii"], a: 0}
    ]
  },
  conta: {
    label: "Contabilitate Financiară",
    questions: [
      {q: "101. Înregistrarea contabilă: 462 = % (7583 şi 4427) semnifică:", o: ["A. vânzarea unei imobilizări parţial amortizate", "B. imputare pentru lipsă", "C. imobilizări corporale date în locație", "D. cedarea imobilizării necorporale/corporale cu preț de vânzare mai mic decât valoarea neamortizată"], a: 3},
      {q: "102. Înregistrarea 1012 = 456 (10.000) reprezintă:", o: ["A. subscrierea capitalului", "B. aport în natură", "C. majorarea capitalului social prin încorporarea rezervelor", "D. vărsarea capitalului"], a: 2},
      {q: "103. Contul 2672 'Dobânzi aferente titlurilor imobilizate' este un cont de:", o: ["A. activ", "B. pasiv", "C. bifuncțional", "D. cheltuieli"], a: 0},
      {q: "104. Obiectivele gestionării trezoreriei sunt:", o: ["A. profitabilitatea", "B. creșterea capitalului", "C. siguranța", "D. asigurarea lichidității și solvabilității"], a: 3},
      {q: "105. Imobilizările necorporale se evaluează la:", o: ["A. valoarea de piață", "B. costul de achiziție sau costul de producție", "C. valoarea de inventar", "D. valoarea justă"], a: 1},
      {q: "106. Cheltuielile cu cercetarea sunt:", o: ["A. imobilizări necorporale", "B. active circulante", "C. cheltuieli ale perioadei", "D. rezerve"], a: 2},
      {q: "107. Rezerva legală se constituie din:", o: ["A. venituri", "B. profitul brut", "C. rezerve din reevaluare", "D. capital"], a: 1},
      {q: "108. Amortizarea reprezintă:", o: ["A. alocarea sistematică a valorii amortizabile pe durata utilă", "B. cheltuială cu întreținerea", "C. o rezervă", "D. un activ"], a: 0},
      {q: "109. Relațiile cu acționarii privind dividendele se înregistrează în:", o: ["A. 457", "B. 401", "C. 512", "D. 101"], a: 0},
      {q: "110. Contul 609 'Cheltuieli privind mărfurile' este utilizat pentru:", o: ["A. achiziții", "B. reduceri comerciale primite ulterior facturării", "C. vânzări", "D. stocuri"], a: 1},
      {q: "111. Cheltuielile de dezvoltare se pot activa dacă:", o: ["A. sunt eligibile", "B. proiectul este fezabil și profitabil", "C. sunt plătite", "D. sunt mici"], a: 1},
      {q: "112. Datoriile cu termen de plată mai mic de 1 an sunt:", o: ["A. imobilizări", "B. datorii pe termen lung", "C. capitaluri", "D. datorii pe termen scurt (curente)"], a: 3},
      {q: "113. La cedarea unei construcții, se utilizează contul:", o: ["A. 704", "B. 6583", "C. 768", "D. 607"], a: 1},
      {q: "114. Avansul de trezorerie se înregistrează în:", o: ["A. 5121", "B. 401", "C. 542", "D. 473"], a: 2},
      {q: "115. Dividendele încasate de la entități afiliate sunt:", o: ["A. venituri financiare", "B. venituri din exploatare", "C. cheltuieli", "D. capital"], a: 0},
      {q: "116. Scoaterea din evidență a obiectelor de inventar se face prin:", o: ["A. 603 = 303", "B. 303 = 603", "C. 603 = 401", "D. 303 = 401"], a: 3},
      {q: "117. Diferențele favorabile de preț la semifabricate sunt:", o: ["A. 341 = 348", "B. 348 = 341", "C. 711 = 348", "D. 341 = 711"], a: 0},
      {q: "118. Mărfurile primite gratuit reprezintă:", o: ["A. venituri financiare", "B. cheltuieli", "C. diminuare de activ", "D. venituri din subvenții/donații (7582)"], a: 3},
      {q: "119. Autocamionul utilizat pentru nevoi proprii este:", o: ["A. marfă", "B. produs finit", "C. obiect de inventar", "D. imobilizare corporală"], a: 3},
      {q: "120. Produsele finite se evaluează la:", o: ["A. cost de producție", "B. preț de vânzare", "C. valoare justă", "D. valoare de inventar"], a: 0},
      {q: "121. Ajustările pentru deprecierea stocurilor sunt:", o: ["A. venituri", "B. cheltuieli de exploatare (6814)", "C. capitaluri", "D. datorii"], a: 1},
      {q: "122. Construcția unei clădiri în regie proprie se înregistrează:", o: ["A. 231 = 722", "B. 212 = 231", "C. 231 = 401", "D. 722 = 231"], a: 0},
      {q: "123. Consumul de materii prime:", o: ["A. 301 = 601", "B. 401 = 301", "C. 301 = 401", "D. 601 = 301"], a: 3},
      {q: "124. Accizele la importul de mărfuri:", o: ["A. se includ în costul de achiziție", "B. sunt cheltuieli", "C. sunt venituri", "D. nu se contabilizează"], a: 0},
      {q: "125. Amortizarea concesiunilor:", o: ["A. 6811 = 2805", "B. 2805 = 6811", "C. 6811 = 2812", "D. 2812 = 6811"], a: 0},
      {q: "126. Plusul la inventar produse finite:", o: ["A. 711 = 345", "B. 345 = 607", "C. 607 = 345", "D. 345 = 711"], a: 3},
      {q: "127. PAM (Preț Achiziție Mediu):", o: ["A. metodă de evaluare a ieșirilor", "B. venit", "C. cheltuială", "D. activ"], a: 0},
      {q: "128. Inventarul permanent presupune:", o: ["A. înregistrarea doar la sfârșitul anului", "B. neînregistrarea stocurilor", "C. evaluarea la preț de vânzare", "D. înregistrarea continuă a intrărilor/ieșirilor"], a: 3},
      {q: "129. Achiziția cu plata prin efect comercial:", o: ["A. 401 = 403", "B. 403 = 401", "C. 301 = 401", "D. 301 = 403"], a: 3},
      {q: "130. Primele de asigurare plătite:", o: ["A. 613 = 5121", "B. 5121 = 613", "C. 471 = 5121", "D. 613 = 401"], a: 2},
      {q: "131. Biletul la ordin este:", o: ["A. act de proprietate", "B. titlu de valoare", "C. instrument de plată (403/413)", "D. cheltuială"], a: 2},
      {q: "132. Cheltuielile înregistrate în avans (471):", o: ["A. 6xx = 471", "B. 471 = 4xx", "C. 512 = 471", "D. 471 = 6xx"], a: 1},
      {q: "133. Creanța clientului în faliment:", o: ["A. 411 = 654", "B. 654 = 411", "C. 491 = 6814", "D. 654 = 411 (scoatere)"], a: 3},
      {q: "134. Repartizarea profitului:", o: ["A. 129 = 1061/117/457", "B. 1061 = 129", "C. 121 = 129", "D. 129 = 121"], a: 0},
      {q: "135. Impozitul pe profit:", o: ["A. 441 = 691", "B. 691 = 441", "C. 691 = 512", "D. 441 = 512"], a: 1},
      {q: "136. Rețeta de fabricație:", o: ["A. document de fundamentare a costului", "B. factură", "C. extras de cont", "D. inventar"], a: 0},
      {q: "137. Amortizarea primelor de emisiune:", o: ["A. nu se amortizează", "B. 686 = 169", "C. 686 = 169 (transfer pe venituri/cheltuieli)", "D. 169 = 686"], a: 2},
      {q: "138. Achitarea datoriei în valută la curs mai mic:", o: ["A. 765", "B. 665", "C. 765 (diferență favorabilă)", "D. 401"], a: 2},
      {q: "139. Avizul de însoțire a mărfii:", o: ["A. act de vânzare", "B. document de circulație", "C. factură", "D. extras"], a: 1},
      {q: "140. Încasarea chiriei:", o: ["A. 706 = 4427", "B. 5121 = 706", "C. 411 = 706", "D. 5121 = 706 + 4427"], a: 3},
      {q: "141. Adaosul comercial:", o: ["A. 371 = 378", "B. 378 = 371", "C. 378 = 4428", "D. 371 = 4428"], a: 2},
      {q: "142. Înregistrarea 161 = 765 reprezintă:", o: ["A. dobândă", "B. diferență nefavorabilă de curs valutar (665)", "C. cheltuială", "D. activ"], a: 1},
      {q: "143. Subscrierea capitalului social:", o: ["A. 1012 = 456", "B. 456 = 1012", "C. 456 = 1011 (subscriere)", "D. 512 = 456"], a: 2},
      {q: "144. Înregistrarea 6581 = 4481:", o: ["A. despăgubiri datorate", "B. subvenții", "C. profit", "D. capital"], a: 0},
      {q: "145. Dobânzile aferente împrumuturilor de la entități afiliate:", o: ["A. 666", "B. 766", "C. 666 (cu conturi analitice)", "D. 512"], a: 3},
      {q: "146. Vânzarea imobilizărilor corporale:", o: ["A. 461 = 7583", "B. 7583 = 461", "C. 281 = 212", "D. 461 = 7583 + 4427"], a: 3},
      {q: "147. Înregistrarea 104 = 106:", o: ["A. transfer rezerve din reevaluare", "B. majorare capital", "C. profit", "D. cheltuială"], a: 0},
      {q: "148. Dobânzile datorate (înregistrare lunară):", o: ["A. 512 = 666", "B. 666 = 1681", "C. 1681 = 666", "D. 666 = 401"], a: 1},
      {q: "149. Încasarea creanței înainte de termen ( scont):", o: ["A. 667", "B. 667 (cheltuieli privind sconturile acordate)", "C. 767", "D. 512"], a: 1},
      {q: "150. Livrarea produselor finite:", o: ["A. 711 = 345", "B. 345 = 711", "C. 411 = 701", "D. 411 = 701 + 4427"], a: 3}
    ]
  },
  bazele: {
    label: "Bazele contabilității",
    questions: [
      {q: "151. Procedeele specifice metodei contabilității sunt următoarele:", o: ["A. Analiza și sinteza", "B. Bilanțul și contul", "C. Documentația, evaluarea, calculația și inventarierea", "D. Niciun răspuns nu este corect"], a: 2},
      {q: "152. Procedeele comune tuturor științelor sunt:", o: ["A. Documentația și inventarierea", "B. Bilanțul și balanța", "C. Observația, raționamentul, comparația, clasificarea, analiza, sinteza", "D. Niciun răspuns nu este corect"], a: 2},
      {q: "153. Ecuația fundamentală a bilanțului este:", o: ["A. Active + Capitaluri = Datorii", "B. Active = Capitaluri proprii + Datorii", "C. Active - Datorii = Cheltuieli", "D. Active = Cheltuieli"], a: 1},
      {q: "154. Activele imobilizate sunt:", o: ["A. Stocurile", "B. Disponibilitățile bănești", "C. Creanțele", "D. Imobilizările corporale, necorporale și financiare"], a: 3},
      {q: "155. Activele circulante sunt:", o: ["A. Construcțiile", "B. Echipamentele", "C. Stocurile, creanțele și disponibilitățile bănești", "D. Capitalul social"], a: 2},
      {q: "156. Principiul prudenței presupune:", o: ["A. Înregistrarea tuturor profiturilor", "B. Nu se supraevaluează activele și nu se subevaluează datoriile", "C. Ignorarea riscurilor", "D. Evaluarea la preț de vânzare"], a: 1},
      {q: "157. Principiul pragului de semnificație:", o: ["A. Evidențierea tuturor operațiunilor", "B. Ignorarea valorilor mici", "C. Evaluarea la cost istoric", "D. Orice eroare sau omisiune care poate influența deciziile trebuie prezentată"], a: 3},
      {q: "158. Capitalul propriu este format din:", o: ["A. Datorii", "B. Credite bancare", "C. Capital social, rezerve și profit/pierdere", "D. Furnizori"], a: 2},
      {q: "159. Distincția activ/cheltuială:", o: ["A. Activul aduce beneficii viitoare, cheltuiala consumă resurse", "B. Activul este cheltuială", "C. Cheltuiala este activ", "D. Nu există distincție"], a: 2},
      {q: "160. Ieșirea stocurilor se poate evalua prin:", o: ["A. Doar FIFO", "B. Doar LIFO", "C. Doar CMP", "D. FIFO, LIFO sau CMP"], a: 3},
      {q: "161. Metoda FIFO presupune:", o: ["A. Primul intrat, primul ieșit", "B. Ultimul intrat, primul ieșit", "C. Cost mediu ponderat", "D. Preț fix"], a: 0},
      {q: "162. Metoda CMP presupune:", o: ["A. Primul intrat, primul ieșit", "B. Ultimul intrat, primul ieșit", "C. Preț de piață", "D. Costul mediu ponderat"], a: 3},
      {q: "163. Nu se includ în cheltuieli:", o: ["A. Consumul de materii prime", "B. Salariile", "C. Dobânzile", "D. Achiziția de imobilizări"], a: 3},
      {q: "164. Nu se includ în capitalurile proprii:", o: ["A. Capitalul social", "B. Rezervele", "C. Împrumuturile bancare", "D. Profitul"], a: 2},
      {q: "165. Nu reprezintă un element de activ:", o: ["A. Împrumuturile primite", "B. Stocurile", "C. Construcțiile", "D. Casa"], a: 0},
      {q: "166. Nu reprezintă o creanță:", o: ["A. Clienți", "B. Furnizori", "C. Debitori diverși", "D. Avansuri acordate"], a: 1},
      {q: "167. Clasificarea activelor după lichiditate (crescător):", o: ["A. Disponibilități -> Stocuri -> Imobilizări", "B. Stocuri -> Imobilizări -> Disponibilități", "C. Imobilizări -> Stocuri -> Disponibilități", "D. Nu se clasifică"], a: 2},
      {q: "168. Egalitatea bilanțieră:", o: ["A. A > P", "B. A < P", "C. A = P", "D. Nu există"], a: 2},
      {q: "169. Încasarea unei creanțe (clienți):", o: ["A. 411 = 5121", "B. 6xx = 411", "C. 5121 = 411", "D. 411 = 7xx"], a: 2},
      {q: "170. Achiziția unui mijloc de transport:", o: ["A. 2133 = 604", "B. 2133 = 404", "C. 604 = 404", "D. 404 = 2133"], a: 1},
      {q: "171. Vânzarea produselor finite:", o: ["A. 411 = 701", "B. 411 = 701 + 4427", "C. 701 = 411", "D. 345 = 701"], a: 1},
      {q: "172. Modificare A+X=P+X (A-P=0):", o: ["A. Sursă de finanțare", "B. Creștere A, Scădere A", "C. Creștere P, Scădere P", "D. Creștere activ și pasiv"], a: 3},
      {q: "173. Modificare A-X=P-X (A-P=0):", o: ["A. Creștere activ și pasiv", "B. Scădere activ și pasiv", "C. Creștere activ", "D. Scădere activ"], a: 2},
      {q: "174. Modificare A=P+X-X (A-P=0):", o: ["A. Creștere/Scădere simultană activ", "B. Creștere activ și pasiv", "C. Scădere activ și pasiv", "D. Nu există"], a: 0},
      {q: "175. Constituirea entității (aport capital):", o: ["A. 456 = 1011", "B. 512 = 1012", "C. 1011 = 1012", "D. 456 = 1011, apoi 512 = 456"], a: 3},
      {q: "176. Amortizarea activelor (cheltuială):", o: ["A. 6811 = 28xx", "B. 28xx = 6811", "C. 6811 = 21xx", "D. 21xx = 6811"], a: 0},
      {q: "177. Amortizare N+3 (val 36.000, 3 ani, liniar):", o: ["A. 12.000", "B. 10.000", "C. 6.000", "D. 0 (complet amortizat)"], a: 3},
      {q: "178. Amortizare N+2 (val 14.400, 4 ani, liniar):", o: ["A. 14.400", "B. 3.600", "C. 7.200", "D. 0"], a: 1},
      {q: "179. Capitaluri permanente:", o: ["A. Capitaluri proprii", "B. Capitaluri proprii + Datorii pe termen lung", "C. Datorii pe termen scurt", "D. Active"], a: 1},
      {q: "180. Activ bilanțier:", o: ["A. Datorii", "B. Imobilizări + Active circulante", "C. Capitaluri proprii", "D. Cheltuieli"], a: 1},
      {q: "181. Conturi bifuncționale:", o: ["A. Doar activ", "B. Doar pasiv", "C. Pot avea sold activ sau pasiv (ex: 401, 411)", "D. Nu există"], a: 2},
      {q: "182. Dubla înregistrare:", o: ["A. Înregistrarea într-un singur cont", "B. Înregistrarea concomitentă în cel puțin două conturi (debit/credit)", "C. Înregistrarea în contul de profit", "D. Nu există"], a: 1},
      {q: "183. 104 = 106:", o: ["A. Transfer rezerve din reevaluare", "B. Majorare capital", "C. Profit", "D. Pierdere"], a: 0},
      {q: "184. Valoare utilaj (cost achiziție):", o: ["A. Preț factură", "B. Preț factură + transport + montaj", "C. Preț factură - transport", "D. Doar preț factură"], a: 2},
      {q: "185. Sold final pasiv:", o: ["A. SFp = SIp + RulajC - RulajD", "B. SFp = SIp + RulajD - RulajC", "C. SFp = SIp", "D. SFp = 0"], a: 0},
      {q: "186. Sold final activ:", o: ["A. SFa = SIa + RulajC - RulajD", "B. SFa = SIa", "C. SFa = 0", "D. SFa = SIa + RulajD - RulajC"], a: 3},
      {q: "187. Sold final 2133 (mijloace transport):", o: ["A. Sold pasiv", "B. Sold activ", "C. Zero", "D. Nu are sold"], a: 1},
      {q: "188. 6811 = 2813 (2.000):", o: ["A. Amortizare utilaje", "B. Achiziție utilaje", "C. Vânzare utilaje", "D. Reparație utilaje"], a: 0},
      {q: "189. Datorie financiară:", o: ["A. Credite bancare", "B. Clienți", "C. Stocuri", "D. Casa"], a: 0},
      {q: "190. Creanțe:", o: ["A. Clienți, Debitori diverși", "B. Furnizori", "C. Rezerve", "D. Capital social"], a: 0},
      {q: "191. Încasare numerar (casa):", o: ["A. 5121 = 5311", "B. 5311 = 411", "C. 5311 = 5121", "D. 411 = 5311"], a: 2},
      {q: "192. Vânzare mărfuri (credit):", o: ["A. 411 = 707 + 4427", "B. 5121 = 707", "C. 707 = 411", "D. 4427 = 411"], a: 1},
      {q: "193. Vânzare mărfuri (valoare 12.100, 19% TVA):", o: ["A. 411 = 707 (12.100)", "B. 411 = 707 (10.000) + 4427 (2.100)", "C. 411 = 707 (12.100)", "D. 707 = 411"], a: 2},
      {q: "194. Achiziție materii prime:", o: ["A. 401 = 301", "B. 301 + 4426 = 401", "C. 301 = 4426", "D. 401 = 4426"], a: 1},
      {q: "195. Amortizare soft (necorporal):", o: ["A. 6811 = 2803", "B. 6811 = 2805", "C. 6811 = 2812", "D. 6811 = 2133"], a: 3},
      {q: "196. 711 = 345:", o: ["A. Producție în curs", "B. Vânzare produse finite", "C. Producție stocată (creștere stoc)", "D. Scădere stoc"], a: 2},
      {q: "197. Modificare A-X=P-X:", o: ["A. Creștere activ", "B. Scădere activ și pasiv", "C. Creștere activ și pasiv", "D. Niciuna"], a: 1},
      {q: "198. Active circulante:", o: ["A. Imobilizări", "B. Stocuri, creanțe, casa", "C. Capital social", "D. Rezerve"], a: 2},
      {q: "199. Amortizare accelerată N+3 (val 30.000, 5 ani):", o: ["A. 12.000 (an 1), 7.200 (an 2), 4.320 (an 3)", "B. 6.000", "C. 0", "D. 10.000"], a: 0},
      {q: "200. Pasiv bilanțier:", o: ["A. Active", "B. Cheltuieli", "C. Capitaluri proprii + Datorii", "D. Venituri"], a: 2}
    ]
  }
};
